config/routes.rb
Rails.application.routes.draw do

  resources :wills do
    get 'final_will'
    resources :testator_details, only: [:new, :edit, :create, :update]
    resources :partner_details, only: [:new, :edit, :create, :update]
    resources :funerals, only: [:new, :edit, :create, :update]
    resources :executors, only: [:new, :edit, :create, :update] do

        get :first_executor
        get :second_executor
        get :third_executor
        get :forth_executor
        get :first_replacement_executor
        get :second_replacement_executor
        get :third_replacement_executor
        get :forth_replacement_executor

    end
    resources :administrations, only: [:new, :edit, :create, :update]
    resources :guardians, only: [:new, :edit, :create, :update] do

        get :option
        get :first_guardian
        get :second_guardian
        get :third_guardian
        get :forth_guardian
        get :first_replacement_guardian
        get :second_replacement_guardian
        get :third_replacement_guardian
        get :forth_replacement_guardian

    end
    resources :cash_gifts, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
    end
    resources :charitable_donations, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
    end
    resources :charity_permissions, only: [:new, :edit, :create, :update]
    resources :properties, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
      get :benificiaries
    end
    resources :personal_gifts, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
    end
    resources :residuaries, only: [:new, :edit, :create, :update]
    resources :residuary_details, only: [:new, :edit, :create, :update, :index] do
        get :charity_benificiary
        get :people_benificiary 
        collection do 
          get :secondary
          get :option
        end
    end
    resources :requests, only: [:new, :edit, :create, :update]
  end

  resources :general_details, only: [:new, :edit, :create, :update]
  resources :questions

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/terms_and_conditions', to: 'static_pages#terms_and_conditions', via: 'get'

  root 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login
  def home
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.haml
-provide(:bodyclass , "home")

#intro
  .narrow-logo
    = image_tag("logo.png")
  %h1 Express Wills: Protect your future
  %h2 Create a Will quickly and easily to ensure your wishes are carried out after your death
  %p= link_to("Create New Will", new_will_path)

app/views/static_pages/terms_and_conditions.html.haml
%p
  %strong EXPRESS WILL
%p
  %strong Terms & Conditions
%p
  In using our services you agree to abide by the following Terms & Conditions:
  %br/
  %br/
  %strong Contractual Parties
  %br/
  %br/
  Services are provided to you by Notary Express Limited trading as Express Will.
  %br/
  %br/
  %strong Payment
  %br/
  %br/
  Payment is due on completion of the online form in order to receive your completed will. We prefer to accept payment by the methods shown on the website, but we can also accommodate cash or cheque payments. Please contact us if you wish to arrange payment in cash or by cheque.
%p
  %strong Probate
%p
  If you opt to appoint us as executors and trustees under your will we will, when you die, charge for the services we provide in accordance with our rates in force at that time. Our rates will be provided to co-executors before any expense is incurred. Alternatively you can appoint non-professional executors which would mean that no legal costs apply.
  %br/
  %br/
  %strong Conduct
  %br/
  %br/
  You agree to provide us with true and accurate information when using the services. We are not responsible for any issues that arise through the provision to us by yourself (or any party instructed to act on your behalf) of incorrect information. You agree to notify us immediately of any unauthorised use of your identity or email that could affect our service to you.
  %br/
  %br/
  %strong Our Responsibilities
  %br/
  %br/
  Our responsibility is limited to processing the information you put into the online form and automatically generating a will from the information you entered. In using our website you agree that you are acting of your own free will not subject to any coercion or undue influence, and that you have the capacity to understand that you are making a will. We do not conduct checks as to the identity, legal capacity, authority and understanding of the user. If you require these checks to be made please contact us for our bespoke offline will service.
%p
  %strong Data Errors
%p We do not accept any liability for spelling mistakes, typographical errors or omissions made on your part or as a result of information you enter on the website. This applies even if your mistake results in an unintended gift or invalidity of any gift or the will itself.
%p When you use our gold service we will check for clearly misspelled words and sentences that do not make any sense in the English language. We do not accept responsibility for misspelled names, incorrect amounts, gifts left to the wrong persons or your failure to enter data into the form in accordance with your intentions, howsoever caused.
%p You are provided with the chance to review the data you have entered before purchase and you take full responsibility for the accuracy of all data you have entered. After your purchase of the will you cannot change the information entered unless you wish to purchase a new will.
%p The wills provided by this website are electronic in form and therefore not possible to return, so once you have received your will no refund will be given.
%p
  %strong Signing Your Will
%p When your will is sent to you we will also provide advice on signing it in accordance with the laws of England and Wales. Signing a will incorrectly can result in costly proceedings on death, the invalidity of the will and/or gifts therein. We exclude liability following for the incorrect signing of a will if our instructions for signing it have not been followed.
%p If you would like confirmation that the will has been correctly signed please email us a copy and subject to payment of our fee we will confirm this.
%p
  %strong Legal Advice
  %br/
  %br/
  This is an automated will generation service, which does not provide legal advice, tax advice or advice on foreign assets. You are advised to seek the relevant professional for advice on these matters.
%p If you have assets situated abroad we strongly advise you use our bespoke offline will service. We do not guarantee the applicability of your will to foreign assets. We exclude all liability for failure to receive assets located in a foreign jurisdiction, howsoever caused.
%p
  %strong Insurance
  %br/
  %br/
  We limit our liability to the amount you paid us for the will, except as a result of death or personal injury.
%p Notary Express carries professional indemnity and fidelity liability cover of £1,000,000.  If the immediately preceding paragraph does not take effect we limit the level of our liability to you to £1,000,000, except as a result of death or personal injury. This limit is considered to be fair and reasonable and reflects the level of professional indemnity insurance we hold. Where in relation to any loss you also have a cause of action against any third party, we shall only be liable to you for our share of the responsibility but not more than the limit on our liability mentioned in this paragraph.
%p
  %strong Third Parties
%p We provide wills for the benefit of the user and their beneficiaries. We exclude liability in relation to any other persons and third parties.
%p  
%p
  %strong Governing Law and Jurisdiction
%p We prepare wills in accordance with the laws of England and Wales and the courts of England have exclusive jurisdiction over any dispute. If you have assets situated abroad the will is unlikely to fulfil your wishes. In this case please contact us about our bespoke offline will service.
%p
  %strong Severance
%p If any clause or part of a clause in this agreement is deemed unlawful and/or enforceable then such part of it will be deemed to be deleted and the rest of the clause or agreement will continue in effect.
%p
  %strong Data Protection
  %br/
  %br/
  Notary Express will in most cases keep an entry of the information entered and an electronic copy of the will. You agree to us retaining this information. We may use this for the purposes of complying with legal and regulatory requirements, to detect, investigate and prevent fraud, for internal analysis and research, and to contact you from time to time with offers of products and services that we believe may be of interest to you. You can opt out of receiving marketing information at any time. We will never pass your details on to third parties unless required to do so by law.
  %br/
  %br/
  %strong Amendment
  %br/
  %br/
  We reserve the right to amend these Terms & Conditions at any time by posting an amended version to this website. The updated Terms & Conditions shall apply to all services rendered since the update.
%p
  %strong Complaints
%p 1. Our legal practice is regulated by the Faculty Office of the Archbishop of Canterbury:
%p
  The Faculty Office
  %br/
  1, The Sanctuary
  %br/
  Westminster
  %br/
  London
  %br/
  SW1P 3JT
%p
  Telephone 0207 222 5381
  %br/
  Email: faculty.office@1thesanctuary.com
  %br/
  Website: www.facultyoffice.org.uk
%p 2. If you are dissatisfied about the service you have received please do not hesitate to contact us.
%p 3. If we are unable to resolve the matter you may complain to the Notaries Society of which I am a member, who have a complaints procedure which is approved by the Faculty Office. This procedure is free to use and is designed to provide a quick resolution to any dispute.
%p
  4. In that case please write (but do not enclose any original documents) with full details of your complaint to:
  %br/
  %br/
  Christopher Vaughan
  %br/
  Secretary of the Notaries Society
  %br/
  Old Church Chambers
  %br/
  23 Sandhill Road
  %br/
  St James
  %br/
  Northampton
  %br/
  NN5 5LH
%p
  Telephone: 0207 222 5381
  %br/
  Email: secretary@thenotariessociety.org.uk
  %br/
  Website: www.thenotariessociety.org.uk
  %br/
   
  %br/
  If you have any difficulty making a complaint in writing, please do not hesitate to call the Notaries Society for assistance. 
%p
  5. Finally, even if you have your complaint considered under the Complaints Procedure, you may at the end of that procedure or after a period of eight weeks from the date you first notified us that you were dissatisfied, make your complaint to the Legal Ombudsman, if you are not happy with the result: 
  %br/
  %br/
  Legal Ombudsman
  %br/
  PO Box 6806
  %br/
  Wolverhampton
  %br/
  WV1 9WJ
  %br/
  %br/
  Telephone: 0300 555 0333
  %br/
  Email: enquiries@legalombudsman.org.uk
  %br/
  Website: www.legalombudsman.org.uk
  %br/
  %br/
  6. If you decide to make a complaint to the Legal Ombudsman, you must refer your matter to the Legal Ombudsman within six months from the conclusion of the complaint process.
%p
  %strong Queries
%p We hope that you will be satisfied with the service we provide but if you have any queries or need our literature provided in a different format please do not hesitate to contact us. We aim to provide the best possible service to the highest standards of practice while ensuring good value to our clients. Thank you for your custom and we hope you will return to use our services again in the future.
%p
%p Merlin Batchelor
%p
  Director & notary public
  %br/
  NOTARY EXPRESS LIMITED
%p Terms & Conditions dated 20 May 2014