config/routes.rb
Rails.application.routes.draw do

  resources :wills do
    get 'final_will'
    resources :testator_details, only: [:new, :edit, :create, :update]
    resources :partner_details, only: [:new, :edit, :create, :update]
    resources :funerals, only: [:new, :edit, :create, :update]
    resources :executors, only: [:new, :edit, :create, :update] do

        get :first_executor
        get :second_executor
        get :third_executor
        get :forth_executor
        get :first_replacement_executor
        get :second_replacement_executor
        get :third_replacement_executor
        get :forth_replacement_executor

    end
    resources :administrations, only: [:new, :edit, :create, :update]
    resources :guardians, only: [:new, :edit, :create, :update] do

        get :option
        get :first_guardian
        get :second_guardian
        get :third_guardian
        get :forth_guardian
        get :first_replacement_guardian
        get :second_replacement_guardian
        get :third_replacement_guardian
        get :forth_replacement_guardian

    end
    resources :cash_gifts, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
    end
    resources :charitable_donations, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
    end
    resources :charity_permissions, only: [:new, :edit, :create, :update]
    resources :properties, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
      get :benificiaries
    end
    resources :personal_gifts, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
    end
    resources :residuaries, only: [:new, :edit, :create, :update]
    resources :residuary_details, only: [:new, :edit, :create, :update, :index] do
        get :charity_benificiary
        get :people_benificiary 
        collection do 
          get :secondary
          get :option
        end
    end
    resources :requests, only: [:new, :edit, :create, :update]
  end

  resources :general_details, only: [:new, :edit, :create, :update]
  resources :questions

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/terms_and_conditions', to: 'static_pages#terms_and_conditions', via: 'get'

  root 'static_pages#home'

end

app/models/charitable_donation.rb
class CharitableDonation < ActiveRecord::Base
  belongs_to :will

    validates :amount, presence: true, :format => { :with => /\A\d+(?:\.\d\d)?\z/ }, :numericality => {:greater_than => 0 }

    validates :name, presence: true, length: { maximum: 200 }, unless: "popular_charity"

    validates :instruction, length: { maximum: 2000 }, allow_blank: true

  def full_name
    self.first_name.titleize {+ " " + self.middle_name.titleize if middle_name} + " " + self.surname.titleize
  end

  def full_address
    self.address_one.titleize {+ ", " + self.address_two.titleize if address_two} + ", " + self.city.titleize + ", " + self.county.titleize + ", " + self.postcode.upcase + ", " + self.country.titleize
  end

end

app/controllers/charitable_donations_controller.rb
class CharitableDonationsController < ApplicationController
  before_action :set_charitable_donation, only: [:show, :edit, :update, :destroy]
  before_action :skip_option, only: [:option]
  after_action only: :option do
    update_will_progress 8
  end

  def new
    @will = Will.find(params[:will_id])
    @charitable_donation = CharitableDonation.new
  end

  def edit
    @will = Will.find(params[:will_id])
  end

  def index
    @will = Will.find(params[:will_id])
    @charitable_donations = @will.charitable_donations
  end

  def create
    @will = Will.find(params[:will_id])
    if @will.charitable_donations.last && @charitable_donation = @will.charitable_donations.find_by(count: params[:charitable_donation][:count])
      @charitable_donation.update(charitable_donation_params)
    else
      @charitable_donation = CharitableDonation.new(charitable_donation_params)
      @charitable_donation.will_id = params[:will_id]
    end
    if @charitable_donation.save
      if params[:commit] == "Add Another"
        redirect_to new_will_charitable_donation_path
      elsif params[:commit] == "Proceed"
        @will = Will.find(params[:will_id])
        redirect_to new_will_charity_permission_path
      end
    else
      render :new
    end
  end

  def update
    @will = Will.find(params[:will_id])
    if @charitable_donation.update(charitable_donation_params)
      redirect_to new_will_charity_permission_path
    else
      render :edit
    end
  end

  def option
    @will = Will.find(params[:will_id])
  end

  def option
  end

  private
  
    def skip_option
      @will = Will.find(params[:will_id])
      @charitable_donations = @will.charitable_donations
      redirect_to will_charitable_donations_path(@will) if @charitable_donations.any?
    end

    def set_charitable_donation
      @charitable_donation = CharitableDonation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def charitable_donation_params
      params.require(:charitable_donation).permit(:count, :charity_id, :amount, :instruction, :allow_alternate, :popular_charity, :popular_charity_name, :name, :registered_charity_number, :address_one, :address_two, :city, :postcode, :county, :country)
    end
end

app/helpers/charitable_donations_helper.rb
module CharitableDonationsHelper
end

app/views/charitable_donations/_form.html.haml
= form_for [@will, @charitable_donation] do |f|
  = render 'layouts/error_messages', object: f.object

  = render "layouts/radio_buttons", :f => f, radio_button: :popular_charity, q_no: "07020", option: {true: "Yes", false: "No"}, selected: 0
  %div{"data-condition" => ":checked", "data-false" => "hide", "data-require" => "#charitable_donation_popular_charity_true", "data-true" => "show"}
    = render "layouts/select_list", :f => f, select_list: :popular_charity_name, q_no: "07030", options: ["Families Need Fathers" , "Arts Council England" , "British Heart Foundation" , "Cancer Research UK" , "Macmillan" , "Royal Society for the Blind" , "Royal Society for the Prevention of Cruelty to Animals" , "The Salvation Army" , "Variety Club" , "Zoological Society of London"], label_text: "Charity Name"

  %div{"data-condition" => ":checked", "data-false" => "show", "data-require" => "#charitable_donation_popular_charity_true", "data-true" => "hide"}
    = render "layouts/text_field", :f => f, text_field: :name, q_no: "00180", origin: @charitable_donation
    = render "layouts/text_field", :f => f, text_field: :registered_charity_number, q_no: "00190", origin: @charitable_donation, label_text: "Registered Charity Number"
    = render "layouts/text_field", :f => f, text_field: :address_one, q_no: "00050", origin: @charitable_donation
    = render "layouts/text_field", :f => f, text_field: :address_two, q_no: "00060", origin: @charitable_donation
    = render "layouts/text_field", :f => f, text_field: :city, q_no: "00070", origin: @charitable_donation
    = render "layouts/text_field", :f => f, text_field: :county, q_no: "00080", origin: @charitable_donation
    = render "layouts/text_field", :f => f, text_field: :postcode, q_no: "00090", origin: @charitable_donation
    = render "layouts/text_field", :f => f, text_field: :country, q_no: "00100", origin: @charitable_donation
  
  = render "layouts/text_field", :f => f, text_field: :amount, q_no: "07040", origin: @charitable_donation
  = render "layouts/text_area", :f => f, text_area: :instruction, advice_text: "You may specify a non-binding purpose for the gift but it is generally advised to leave this box blank so that the charity can put your gift towards any use and ensure it does not take effect if the charity is unable to comply with your request.", q_no: "07050"
  
  = f.hidden_field :count, value: @will.charitable_donations.count+1
  = link_to("Save and Continue", "javascript:void(0)", class: "button radius modal-continue-button")
  = link_to 'Proceed Without Saving', new_will_charity_permission_path, class: "button radius cancel-forward right"

  .modal-continue
    Do you wish to add another?
    .button-region
      = f.submit 'Add Another', class: "button radius"
      = f.submit 'Proceed', class: "button radius"
      = link_to 'Cancel', "javascript:void(0)", class: "button radius cancel-forward modal-cancel"

app/views/charitable_donations/_header.html.haml
%h1 Charitable Donations
%h4.subheader You can make cash gifts to charities.
%hr

app/views/charitable_donations/edit.html.haml
= render 'header'
= render 'form'

app/views/charitable_donations/index.html.haml
- provide(:title, "Charitable Donations")
= render 'header'
%table
  %thead
    %tr
      %th 
        %h5 Donation
      %th 
        %h5 Amount
  %tbody
    - @charitable_donations.each_with_index do |charitable_donation, i|
      %tr
        %td= link_to("Donation #{i}", edit_will_charitable_donation_path(@will, charitable_donation))
        %td= charitable_donation.amount

= link_to("Add Donation", new_will_charitable_donation_path, class: "button radius")
= link_to("Proceed", new_will_charity_permission_path, class: "button radius")

app/views/charitable_donations/option.html.haml
= render 'header'
%dl
  %dt
    = question "07010"

= link_to("No", option_will_properties_path(@will), class: "button radius")
= link_to("Yes", new_will_charitable_donation_path, class: "button radius")