config/routes.rb
Rails.application.routes.draw do

  resources :wills do
    get 'final_will'
    resources :testator_details, only: [:new, :edit, :create, :update]
    resources :partner_details, only: [:new, :edit, :create, :update]
    resources :funerals, only: [:new, :edit, :create, :update]
    resources :executors, only: [:new, :edit, :create, :update] do

        get :first_executor
        get :second_executor
        get :third_executor
        get :forth_executor
        get :first_replacement_executor
        get :second_replacement_executor
        get :third_replacement_executor
        get :forth_replacement_executor

    end
    resources :administrations, only: [:new, :edit, :create, :update]
    resources :guardians, only: [:new, :edit, :create, :update] do

        get :option
        get :first_guardian
        get :second_guardian
        get :third_guardian
        get :forth_guardian
        get :first_replacement_guardian
        get :second_replacement_guardian
        get :third_replacement_guardian
        get :forth_replacement_guardian

    end
    resources :cash_gifts, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
    end
    resources :charitable_donations, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
    end
    resources :charity_permissions, only: [:new, :edit, :create, :update]
    resources :properties, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
      get :benificiaries
    end
    resources :personal_gifts, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
    end
    resources :residuaries, only: [:new, :edit, :create, :update]
    resources :residuary_details, only: [:new, :edit, :create, :update, :index] do
        get :charity_benificiary
        get :people_benificiary 
        collection do 
          get :secondary
          get :option
        end
    end
    resources :requests, only: [:new, :edit, :create, :update]
  end

  resources :general_details, only: [:new, :edit, :create, :update]
  resources :questions

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/terms_and_conditions', to: 'static_pages#terms_and_conditions', via: 'get'

  root 'static_pages#home'

end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :will

  has_one :benificiary_general_details, class_name: "GeneralDetail", foreign_key: "benificiary_id"
  has_one :second_benificiary_general_details, class_name: "GeneralDetail", foreign_key: "second_benificiary_id"
  has_one :third_benificiary_general_details, class_name: "GeneralDetail", foreign_key: "third_benificiary_id"
  has_one :forth_benificiary_general_details, class_name: "GeneralDetail", foreign_key: "forth_benificiary_id"
  has_one :replacement_benificiary_general_details, class_name: "GeneralDetail", foreign_key: "replacement_benificiary_id"
  has_one :second_replacement_benificiary_general_details, class_name: "GeneralDetail", foreign_key: "second_replacement_benificiary_id"
  has_one :third_replacement_benificiary_general_details, class_name: "GeneralDetail", foreign_key: "third_replacement_benificiary_id"
  has_one :forth_replacement_benificiary_general_details, class_name: "GeneralDetail", foreign_key: "forth_replacement_benificiary_id"

  accepts_nested_attributes_for :benificiary_general_details
  accepts_nested_attributes_for :second_benificiary_general_details
  accepts_nested_attributes_for :third_benificiary_general_details
  accepts_nested_attributes_for :forth_benificiary_general_details
  accepts_nested_attributes_for :replacement_benificiary_general_details
  accepts_nested_attributes_for :second_replacement_benificiary_general_details
  accepts_nested_attributes_for :third_replacement_benificiary_general_details
  accepts_nested_attributes_for :forth_replacement_benificiary_general_details

  validates :land_reg_number, length: { maximum: 20 }, allow_blank: true
  validates :postcode, presence: true, length: { maximum: 10 }
  validates :address_one, presence: true, length: { maximum: 100 }
  validates :address_two, length: { maximum: 100 }, allow_blank: true
  validates :city, presence: true, length: { maximum: 100 }
  validates :county, presence: true, length: { maximum: 100 }
  validates :country, presence: true, length: { maximum: 100 }

  def full_address
    self.address_one.titleize {+ ", " + self.address_two.titleize if address_two} + ", " + self.city.titleize + ", " + self.county.titleize + ", " + self.postcode.upcase + ", " + self.country.titleize
  end

  def beneficiaries
    array = []
    array << self.benificiary_general_details if self.benificiary_general_details
    array << self.second_benificiary_general_details if self.second_benificiary_general_details
    array << self.third_benificiary_general_details if self.third_benificiary_general_details
    array << self.forth_benificiary_general_details if self.forth_benificiary_general_details
    return array
  end

  def life_beneficiaries
    array = []
    array << self.replacement_benificiary_general_details if self.replacement_benificiary_general_details
    array << self.second_replacement_benificiary_general_details if self.second_replacement_benificiary_general_details
    array << self.third_replacement_benificiary_general_details if self.third_replacement_benificiary_general_details
    array << self.forth_replacement_benificiary_general_details if self.forth_replacement_benificiary_general_details
    return array
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :skip_option, only: [:option]
  after_action only: :option do
    update_will_progress 10
  end

  def new
    @will = Will.find(params[:will_id])
    @property = Property.new
  end

  def edit
    @will = Will.find(params[:will_id])
  end

  def index
    @will = Will.find(params[:will_id])
    @properties = @will.properties
  end

  def create
    @will = Will.find(params[:will_id])
    if @will.properties.last && @property = @will.properties.find_by(count: params[:property][:count])
      @property.update(property_params)
    else
      @property = Property.new(property_params)
      @property.will_id = params[:will_id]
    end
    if @property.save
      redirect_to will_property_benificiaries_path(@will, @property)
    else
      render :new
    end
  end

  def update
    @will = Will.find(params[:will_id])
    if @property.update(property_params)
      if params[:commit] == "Add Another"
        redirect_to new_will_property_path
      elsif params[:commit] == "Proceed"
        @will = Will.find(params[:will_id])
        redirect_to option_will_personal_gifts_path(@will)
      else
        redirect_to will_property_benificiaries_path(@will, @property)
      end
    else
      if params[:action] == "edit"
        render :edit
      else
        render :benificiaries
      end
    end
  end

  def option
    @will = Will.find(params[:will_id])
  end

  def benificiaries
    @will = Will.find(params[:will_id])
    @property = Property.find(params[:property_id])
    @b1 = @property.benificiary_general_details || @property.build_benificiary_general_details
    @b2 = @property.second_benificiary_general_details || @property.build_second_benificiary_general_details if @property.recipient_no > 1
    @b3 = @property.third_benificiary_general_details || @property.build_third_benificiary_general_details if @property.recipient_no > 2
    @b4 = @property.forth_benificiary_general_details || @property.build_forth_benificiary_general_details if @property.recipient_no > 3
    @b5 = @property.replacement_benificiary_general_details || @property.build_replacement_benificiary_general_details
    @b6 = @property.second_replacement_benificiary_general_details || @property.build_second_replacement_benificiary_general_details if @property.life_beneficiary_no > 1
    @b7 = @property.third_replacement_benificiary_general_details || @property.build_third_replacement_benificiary_general_details if @property.life_beneficiary_no > 2
    @b8 = @property.forth_replacement_benificiary_general_details || @property.build_forth_replacement_benificiary_general_details if @property.life_beneficiary_no > 3
  end

  def option
  end

  private
  
    def skip_option
      @will = Will.find(params[:will_id])
      @properties = @will.properties
      redirect_to will_properties_path(@will) if @properties.any?
    end
    
    def set_property
      @property = Property.find(params[:id])
    end

    def property_params
      params.require(:property).permit(:complete, :count, :sole_residence, :recipient_no, :joint_or_common, :responsible_for_charges, :as_cash_if_sold, :held_in_trust, :life_beneficiary_no, :will_id, :land_reg_number, :address_one, :address_two, :city, :county, :country, :postcode,
        benificiary_general_details_attributes: [:id, :will_id, :relationship, :first_name, :middle_name, :surname, :address_one, :address_two, :city, :county, :postcode, :country],
        second_benificiary_general_details_attributes: [:id, :will_id, :relationship, :first_name, :middle_name, :surname, :address_one, :address_two, :city, :county, :postcode, :country],
        third_benificiary_general_details_attributes: [:id, :will_id, :relationship, :first_name, :middle_name, :surname, :address_one, :address_two, :city, :county, :postcode, :country],
        forth_benificiary_general_details_attributes: [:id, :will_id, :relationship, :first_name, :middle_name, :surname, :address_one, :address_two, :city, :county, :postcode, :country],
        replacement_benificiary_general_details_attributes: [:id, :will_id, :relationship, :first_name, :middle_name, :surname, :address_one, :address_two, :city, :county, :postcode, :country],
        second_replacement_benificiary_general_details_attributes: [:id, :will_id, :relationship, :first_name, :middle_name, :surname, :address_one, :address_two, :city, :county, :postcode, :country],
        third_replacement_benificiary_general_details_attributes: [:id, :will_id, :relationship, :first_name, :middle_name, :surname, :address_one, :address_two, :city, :county, :postcode, :country],
        forth_replacement_benificiary_general_details_attributes: [:id, :will_id, :relationship, :first_name, :middle_name, :surname, :address_one, :address_two, :city, :county, :postcode, :country])
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.haml
%p.section-text You can donate buildings or land that you own as a tenant in common. If you are not sure by what method you own property you can contact Notary Express to make enquiries on your behalf.
%hr
= form_for [@will, @property] do |f|

  = render "layouts/text_field", :f => f, text_field: :land_reg_number, q_no: "00110", origin: @property, label_text: "Land Registry Number"
  = render "layouts/text_field", :f => f, text_field: :address_one, origin: @property
  = render "layouts/text_field", :f => f, text_field: :address_two, origin: @property
  = render "layouts/text_field", :f => f, text_field: :city, origin: @property
  = render "layouts/text_field", :f => f, text_field: :county, origin: @property
  = render "layouts/text_field", :f => f, text_field: :postcode, origin: @property
  = render "layouts/text_field", :f => f, text_field: :country, origin: @property
  = render "layouts/radio_buttons", :f => f, radio_button: :sole_residence, q_no: "08020", option: {true: "Yes", false: "No"}, selected: 0
  = render "layouts/radio_buttons", :f => f, radio_button: :recipient_no, q_no: "08030", option: {1 => "1", 2 => "2", 3 => "3", 4 => "4"}, selected: 0
  %div{"data-condition" => ":checked", "data-true" => "hide", "data-require" => "#property_recipient_no_1", "data-false" => "show"}
    = render "layouts/radio_buttons", :f => f, radio_button: :joint_or_common, advice_text: "Joint tenants hold equal, undivided rights in the property and on the death of one that individual's share automatically passes in equal proportions to the other joint tenants. Tenants in common can control and dispose of their interests individually. If you need further detail or wish to make provision for the recipients in something other than equal shares please contact Notary Express.", q_no: "08040", option: {tenants_in_common: "Tenants in common", joint_tennants: "Joint tenants"}, selected: 1
  = render "layouts/radio_buttons", :f => f, radio_button: :responsible_for_charges, advice_text: "Answering 'no' means your estate will pay the charges, increasing the value of the gift", q_no: "08050", option: {true: "Yes", false: "No"}, selected: 0
  = render "layouts/radio_buttons", :f => f, radio_button: :as_cash_if_sold, q_no: "08060", option: {true: "Yes", false: "No"}, selected: 0
  = render "layouts/radio_buttons", :f => f, radio_button: :held_in_trust, q_no: "08070", option: {true: "Yes", false: "No"}, selected: 0
  %div{"data-condition" => ":checked", "data-false" => "hide", "data-require" => "#property_held_in_trust_true", "data-true" => "show"}
    = render "layouts/select_list", :f => f, select_list: :life_beneficiary_no, advice_text: "This allows named individuals other than the ultimate recipients of the property to live there for the duration of their lives and during this time excludes the ultimate recipients from dealing with the property", q_no: "08080", options: ["1", "2", "3", "4"]
  = f.hidden_field :count, value: @will.properties.count+1
  .button-region
    = f.submit 'Save', class: "button radius"
    

app/views/properties/_header.html.haml
%h1 Property
%h4.subheader You can donate buildings or land that you own as a tenant in common. If you are not sure by what method you own property you can contact Notary Express to make enquiries on your behalf.
%hr

app/views/properties/benificiaries.html.haml
= render 'header'
= form_for [@will, @property] do |f|
  %h3 First Beneficiary
  = f.fields_for :benificiary_general_details do |builder|
    = render "general_details/general_details_form", :builder => builder, :nested_origin => @property.benificiary_general_details
  - if @property.recipient_no > 1
    %h3 Second Beneficiary
    = f.fields_for :second_benificiary_general_details do |builder|
      = render "general_details/general_details_form", :builder => builder, :nested_origin => @property.second_benificiary_general_details
  - if @property.recipient_no > 2
    %h3 Third Beneficiary
    = f.fields_for :third_benificiary_general_details do |builder|
      = render "general_details/general_details_form", :builder => builder, :nested_origin => @property.third_benificiary_general_details
  - if @property.recipient_no > 3
    %h4 Forth Beneficiary
    = f.fields_for :forth_benificiary_general_details do |builder|
      = render "general_details/general_details_form", :builder => builder, :nested_origin => @property.forth_benificiary_general_details
  - if @property.held_in_trust  
    - if @property.life_beneficiary_no > 0
      %h3 First Life Beneficiary
      = f.fields_for :replacement_benificiary_general_details do |builder|
        = render "general_details/general_details_form", :builder => builder, :nested_origin => @property.replacement_benificiary_general_details
    - if @property.life_beneficiary_no > 1
      %h3 Second Life Beneficiary
      = f.fields_for :second_replacement_benificiary_general_details do |builder|
        = render "general_details/general_details_form", :builder => builder, :nested_origin => @property.replacement_benificiary_general_details
    - if @property.life_beneficiary_no > 2
      %h3 Third Life Beneficiary
      = f.fields_for :third_replacement_benificiary_general_details do |builder|
        = render "general_details/general_details_form", :builder => builder, :nested_origin => @property.replacement_benificiary_general_details
    - if @property.life_beneficiary_no > 3
      %h3 Forth Life Beneficiary
      = f.fields_for :forth_replacement_benificiary_general_details do |builder|
        = render "general_details/general_details_form", :builder => builder, :nested_origin => @property.replacement_benificiary_general_details
  = f.hidden_field :complete, value: true

  = f.hidden_field :count, value: @will.properties.count
  = link_to("Save and Continue", "javascript:void(0)", class: "button radius modal-continue-button")
  = link_to 'Proceed Without Saving', option_will_personal_gifts_path(@will), class: "button radius cancel-forward right"

  .modal-continue
    Do you wish to add another?
    .button-region
      = f.submit 'Add Another', class: "button radius"
      = f.submit 'Proceed', class: "button radius"
      = link_to 'Cancel', "javascript:void(0)", class: "button radius cancel-forward modal-cancel"

app/views/properties/edit.html.haml
= render 'header'
= render 'form'

app/views/properties/index.html.haml
- provide(:title, "Property")

= render 'header'


%table
  %thead
    %tr
      %th 
        %h5 Property
  %tbody
    - @properties.where(complete: true).each_with_index do |property, i|
      %tr
        %td= link_to(property.postcode, edit_will_property_path(@will, property))

= link_to("Add Property", new_will_property_path, class: "button radius")
= link_to("Proceed", option_will_personal_gifts_path(@will), class: "button radius")

app/views/properties/new.html.haml
= render 'header'
= render 'form'

app/views/properties/option.html.haml
= render 'header'
%dl
  %dt
    = question "08010"
  %p.advice If you do not make a specific gift of any building or land you own it will pass to any beneficiaries you choose to receive the remainder of your estate if you own the full interest of the property or hold it as a tenant in common
= link_to("No", option_will_personal_gifts_path(@will), class: "button radius")
= link_to("Yes", new_will_property_path, class: "button radius")