config/routes.rb
Rails.application.routes.draw do

  resources :wills do
    get 'final_will'
    resources :testator_details, only: [:new, :edit, :create, :update]
    resources :partner_details, only: [:new, :edit, :create, :update]
    resources :funerals, only: [:new, :edit, :create, :update]
    resources :executors, only: [:new, :edit, :create, :update] do

        get :first_executor
        get :second_executor
        get :third_executor
        get :forth_executor
        get :first_replacement_executor
        get :second_replacement_executor
        get :third_replacement_executor
        get :forth_replacement_executor

    end
    resources :administrations, only: [:new, :edit, :create, :update]
    resources :guardians, only: [:new, :edit, :create, :update] do

        get :option
        get :first_guardian
        get :second_guardian
        get :third_guardian
        get :forth_guardian
        get :first_replacement_guardian
        get :second_replacement_guardian
        get :third_replacement_guardian
        get :forth_replacement_guardian

    end
    resources :cash_gifts, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
    end
    resources :charitable_donations, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
    end
    resources :charity_permissions, only: [:new, :edit, :create, :update]
    resources :properties, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
      get :benificiaries
    end
    resources :personal_gifts, only: [:new, :edit, :create, :update, :index] do
      collection { get :option }
    end
    resources :residuaries, only: [:new, :edit, :create, :update]
    resources :residuary_details, only: [:new, :edit, :create, :update, :index] do
        get :charity_benificiary
        get :people_benificiary 
        collection do 
          get :secondary
          get :option
        end
    end
    resources :requests, only: [:new, :edit, :create, :update]
  end

  resources :general_details, only: [:new, :edit, :create, :update]
  resources :questions

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/terms_and_conditions', to: 'static_pages#terms_and_conditions', via: 'get'

  root 'static_pages#home'

end

app/models/residuary_detail.rb
class ResiduaryDetail < ActiveRecord::Base
  has_one :individual_residuary_general_detail, class_name: "GeneralDetail", foreign_key: "individual_residuary_id"
  has_one :charity_residuary_general_detail, class_name: "CharityDetail", foreign_key: "charity_residuary_id"

  accepts_nested_attributes_for :individual_residuary_general_detail
  accepts_nested_attributes_for :charity_residuary_general_detail
end

app/controllers/residuary_details_controller.rb
class ResiduaryDetailsController < ApplicationController
  before_action :set_residuary_detail, only: [:show, :edit, :update, :destroy]
  before_action :skip_option, only: [:option]
  before_action only: :new do
    update_will_progress 12
  end

  def new
    @will = Will.find(params[:will_id])
    @residuary_detail = ResiduaryDetail.new
  end

  def secondary
    @will = Will.find(params[:will_id])
    @residuary_detail = ResiduaryDetail.new
  end

  def edit
    @will = Will.find(params[:will_id])
    @resgen = @residuary_detail.individual_residuary_general_detail || @residuary_detail.build_individual_residuary_general_detail
    @resgens = @residuary_detail.charity_residuary_general_detail || @residuary_detail.build_charity_residuary_general_detail
  end

  def index
    @will = Will.find(params[:will_id])
    @residuary_details = @will.residuary_details.where(complete:true)
  end

  def create
    @will = Will.find(params[:will_id])
    if @will.residuary_details.last && @residuary_detail = @will.residuary_details.find_by(count: params[:residuary_detail][:count])
      @residuary_detail.update(residuary_detail_params)
    else
      @residuary_detail = ResiduaryDetail.new(residuary_detail_params)
      @residuary_detail.will_id = params[:will_id]
    end
    if @residuary_detail.save
      if @residuary_detail.residuary_type == "I do not wish to specify a beneficiary"
        redirect_to new_will_request_path
      elsif @residuary_detail.residuary_type == "Charity"
        redirect_to will_residuary_detail_charity_benificiary_path(@will, @residuary_detail)
      else
        redirect_to will_residuary_detail_people_benificiary_path(@will, @residuary_detail)
      end
    else
      render :new
    end
  end

  def update
    @will = Will.find(params[:will_id])
    if @residuary_detail.update(residuary_detail_params)
      if params[:commit] == "Submit"
        redirect_to will_residuary_details_path(@will)
      elsif params[:commit] == "Add Another"
        if @residuary_detail.secondary
          redirect_to secondary_will_residuary_details_path
        else
          redirect_to new_will_residuary_detail_path
        end
      elsif params[:commit] == "Proceed"
        if @residuary_detail.secondary
          redirect_to new_will_request_path
        else
          redirect_to new_will_residuary_path
        end
      elsif @residuary_detail.residuary_type == "I do not wish to specify a beneficiary"
        redirect_to new_will_request_path
      elsif @residuary_detail.residuary_type == "Charity"
        redirect_to will_residuary_detail_charity_benificiary_path(@will, @residuary_detail)
      else
        redirect_to will_residuary_detail_people_benificiary_path(@will, @residuary_detail)
      end
    else
      if @residuary_detail.residuary_type == "Individual" || @residuary_detail.residuary_type == "My children"||@residuary_detail.residuary_type == "My grandchildren"
        render :people_benificiary
      elsif @residuary_detail.residuary_type == "Charity"
        render :charity_benificiary
      else
        render :edit
      end
    end
  end

  def people_benificiary
    @will = Will.find(params[:will_id])
    @residuary_detail = ResiduaryDetail.find(params[:residuary_detail_id])
    @resgen = @residuary_detail.individual_residuary_general_detail || @residuary_detail.build_individual_residuary_general_detail
  end

  def charity_benificiary
    @will = Will.find(params[:will_id])
    @residuary_detail = ResiduaryDetail.find(params[:residuary_detail_id])
    @resgen = @residuary_detail.charity_residuary_general_detail || @residuary_detail.build_charity_residuary_general_detail
  end

  def option
  end

  private
  
    def skip_option
      @will = Will.find(params[:will_id])
      @residuary_details = @will.residuary_details
      if @residuary_details.any?
        redirect_to will_residuary_details_path(@will)
      else
        redirect_to new_will_residuary_detail_path(@will)
      end
    end

    def set_residuary_detail
      @residuary_detail = ResiduaryDetail.find(params[:id])
    end

    def residuary_detail_params
      params.require(:residuary_detail).permit(:secondary, :complete, :count, :share, :certain_age, :if_dead, :if_dead_certain_age, :residuary_type,
        individual_residuary_general_detail_attributes: [:id, :will_id, :relationship, :first_name, :middle_name, :surname, :address_one, :address_two, :city, :county, :postcode, :country], 
        charity_residuary_general_detail_attributes: [:id, :will_id, :relationship, :first_name, :middle_name, :surname, :address_one, :address_two, :city, :county, :postcode, :country, :name, :registered_charity_number])
    end
end

app/helpers/residuary_details_helper.rb
module ResiduaryDetailsHelper
end

app/views/residuary_details/_form.html.haml
= form_for [@will, @residuary_detail] do |f|

  =# render "layouts/select_list", :f => f, select_list: :certain_age, q_no: "10030", options: ["no"] + (16..40).to_a.map {|i| i.to_s}, label_text: "Certain Age"
  =# render "layouts/select_list", :f => f, select_list: :if_dead_certain_age, q_no: "10050", options: ["no"] + (16..40).to_a.map {|i| i.to_s}, label_text: "Certain Age"

  = render "layouts/select_list", :f => f, select_list: :residuary_type, q_no: "10010", options: ["Charity" , "Individual" , "My children", "My grandchildren" , "I do not wish to specify a beneficiary"], label_text: "Residuary Type"
  = f.hidden_field :count, value: @will.residuary_details.count+1
  = f.submit 'Save', class: "button radius"

app/views/residuary_details/_header.html.haml
%h1 Residuary
%h4.subheader The residuary is the remainder of your estate after all debts, expenses, taxes and specific gifts have been dealt with. It is often the main gift in your estate.
%hr

app/views/residuary_details/charity_benificiary.html.haml
= render 'header'
= form_for [@will, @residuary_detail] do |f|

  = f.fields_for :charity_residuary_general_detail do |builder|
    = render "charity_details/charity_details_form", :builder => builder, :nested_origin => @residuary_detail.charity_residuary_general_detail

  - @option ||= ["Equal shares", "Trustees to decide"]
  - @start = 100
  - @residuary_detail.secondary ? @res = @will.residuary_details.where(secondary: true) : @res = @will.residuary_details.where(secondary: false)
  - @res.each { |x| @start -= x.share.gsub('%','').to_i if x.share.present? } 
  = render "layouts/select_list", :f => f, select_list: :share, q_no: "10020", options: @option + (1..@start).to_a.map {|i| "#{i.to_s}%"}

  = f.hidden_field :complete, value: true
  .button-region
    = link_to("Save and Continue", "javascript:void(0)", class: "button radius modal-continue-button")
  .modal-continue
    Do you wish to add another?
    .button-region
      = f.submit 'Add Another', class: "button radius"
      - if @residuary_detail.secondary 
        = f.submit 'Submit', class: "button radius" 
      - else
        = f.submit 'Proceed', class: "button radius"
      = link_to 'Cancel', "javascript:void(0)", class: "button radius cancel-forward modal-cancel"

app/views/residuary_details/edit.html.haml
= render 'header'
- if @residuary_detail.residuary_type == "Charity"
  = form_for [@will, @residuary_detail] do |f|

    = f.fields_for :charity_residuary_general_detail do |builder|
      = render "charity_details/charity_details_form", :builder => builder, :nested_origin => @residuary_detail.charity_residuary_general_detail

    - @start = 100 + @residuary_detail.share.gsub('%','').to_i
    - @residuary_detail.secondary ? @res = @will.residuary_details.where(secondary: true) : @res = @will.residuary_details.where(secondary: false)
    - @res.each { |x| @start -= x.share.gsub('%','').to_i if x.share.present? } 
    = render "layouts/select_list", :f => f, select_list: :share, q_no: "10020", options: ["Equal shares", "Trustees to decide"] + (1..@start).to_a.map {|i| "#{i.to_s}%"}

    = f.hidden_field :count, value: @will.residuary_details.count
    = f.hidden_field :complete, value: true
    = f.submit 'Add Another', class: "button radius"
    = f.submit 'Submit', class: "button radius"
- else
  = form_for [@will, @residuary_detail] do |f|

    - if @residuary_detail.residuary_type == "Individual"
      = f.fields_for :individual_residuary_general_detail do |builder|
        = render "general_details/general_details_form", :builder => builder, :nested_origin => @residuary_detail.individual_residuary_general_detail

    - @start = 100 + @residuary_detail.share.gsub('%','').to_i
    - @residuary_detail.secondary ? @res = @will.residuary_details.where(secondary: true) : @res = @will.residuary_details.where(secondary: false)
    - @res.each { |x| @start -= x.share.gsub('%','').to_i if x.share.present? } 
    = render "layouts/select_list", :f => f, select_list: :share, q_no: "10020", options: ["Equal shares", "Trustees to decide"] + (1..@start).to_a.map {|i| "#{i.to_s}%"}

    = render "layouts/select_list", :f => f, select_list: :certain_age, q_no: "10030", options: ["no"] + (16..40).to_a.map {|i| i.to_s}, label_text: "Certain Age"
    = render "layouts/radio_buttons", :f => f, radio_button: :if_dead, q_no: "10040", option: {put_back_into_your_estate: "Put back into your estate", allocated_to_their_children: "Allocated to their child(ren)"}, selected: 0, label_text: "Certain Age"
    = render "layouts/select_list", :f => f, select_list: :if_dead_certain_age, q_no: "10050", options: ["no"] + (16..40).to_a.map {|i| i.to_s}, label_text: "Certain Age"
    = f.hidden_field :count, value: @will.residuary_details.count
    = f.hidden_field :complete, value: true
    = f.submit 'Add Another', class: "button radius"
    = f.submit 'Submit', class: "button radius"

app/views/residuary_details/index.html.haml
- provide(:title, "Residuaries")

= render 'header'

- @correct_total = false
- @total_percent = 0
- @residuary_details.where(secondary: false).each do |x|
  - if x.share == "Equal shares" || x.share == "Trustees to decide"
    - @correct_total = true 
  - else
    - @total_percent += x.share.gsub('%','').to_i

- unless @correct_total == true || @total_percent == 100
  %p To proceed, your residuary share must total 100%, or have at least one residuary with a share of "Equal Shares", or "Trustees to Decide"

%table
  %thead
    %tr
      %th 
        %h5 Residuary
      %th 
        %h5 Share
  %tbody
    - @residuary_details.where(secondary: false).each_with_index do |residuary_detail, i|
      %tr
        %td= link_to(residuary_detail.residuary_type, edit_will_residuary_detail_path(@will, residuary_detail))
        %td= residuary_detail.share

%table
  %thead
    %tr
      %th 
        %h5 Residuary
      %th 
        %h5 Share
  %tbody
    - @residuary_details.where(secondary: true).each_with_index do |residuary_detail, i|
      %tr
        %td= link_to(residuary_detail.residuary_type, edit_will_residuary_detail_path(@will, residuary_detail))
        %td= residuary_detail.share

= link_to("Add Beneficiary", new_will_residuary_detail_path, class: "button radius")
= link_to("Add Secondary Beneficiary", secondary_will_residuary_details_path(@will), class: "button radius")
- if @correct_total == true || @total_percent == 100
  - if @will.residuary
    = link_to("Proceed", new_will_request_path, class: "button radius")
  - else
    = link_to("Proceed", new_will_residuary_path, class: "button radius")

app/views/residuary_details/new.html.haml
= render 'header'

= render 'form'

app/views/residuary_details/people_benificiary.html.haml
= render 'header'

= form_for [@will, @residuary_detail] do |f|

  - if @residuary_detail.residuary_type == "Individual"
    = f.fields_for :individual_residuary_general_detail do |builder|
      = render "general_details/general_details_form", :builder => builder, :nested_origin => @residuary_detail.individual_residuary_general_detail

  
  - if @will.residuary_details.any?
    - @will.residuary_details.each do |x|
      - if x.share == "Equal shares"
        - @option ||= ["Equal shares"]
      - elsif x.share == "Trustees to decide"
        - @option ||= ["Trustees to decide"]

  - @option ||= ["Equal shares", "Trustees to decide"]
  - @start = 100
  - @residuary_detail.secondary ? @res = @will.residuary_details.where(secondary: true) : @res = @will.residuary_details.where(secondary: false)
  - @res.each { |x| @start -= x.share.gsub('%','').to_i if x.share.present? } 
  = render "layouts/select_list", :f => f, select_list: :share, q_no: "10020", options: @option + (1..@start).to_a.map {|i| "#{i.to_s}%"}

  = render "layouts/select_list", :f => f, select_list: :certain_age, q_no: "10030", options: ["no"] + (16..40).to_a.map {|i| i.to_s}, label_text: "Certain Age"
  = render "layouts/radio_buttons", :f => f, radio_button: :if_dead, q_no: "10040", option: {put_back_into_your_estate: "Put back into your estate", allocated_to_their_children: "Allocated to their child(ren)"}, selected: 0
  %div{"data-condition" => ":checked", "data-false" => "show", "data-require" => "#residuary_detail_if_dead_put_back_into_your_estate", "data-true" => "hide"}
    = render "layouts/select_list", :f => f, select_list: :if_dead_certain_age, q_no: "10050", options: ["no"] + (16..40).to_a.map {|i| i.to_s}, label_text: "Certain Age"
  = f.hidden_field :count, value: @will.residuary_details.count
  = f.hidden_field :complete, value: true
  .button-region
    = link_to("Save and Continue", "javascript:void(0)", class: "button radius modal-continue-button")
  .modal-continue
    Do you wish to add another?
    .button-region
      = f.submit 'Add Another', class: "button radius"
      - if @residuary_detail.secondary 
        = f.submit 'Submit', class: "button radius" 
      - else
        = f.submit 'Proceed', class: "button radius"
      = link_to 'Cancel', "javascript:void(0)", class: "button radius cancel-forward modal-cancel"

app/views/residuary_details/secondary.html.haml
%h1 Secondary Residuary
%h4.subheader It is advised you consider secondary beneficiaries in case your primary beneficiaries are not able to receive your residuary estate for any reason.
%hr
= form_for [@will, @residuary_detail] do |f|
  = render "layouts/select_list", :f => f, select_list: :residuary_type, q_no: "10080", options: ["Charity" , "Individual" , "My children", "My grandchildren" , "I do not wish to specify a beneficiary"], label_text: "Residuary Type" 
  = f.hidden_field :count, value: @will.residuary_details.count+1
  = f.hidden_field :secondary, value: true
  = f.submit 'Save', class: "button radius"